# Use root/example as user/password credentials
version: '3.1'

services:

  node:
    image: macterra/tesseract-node
    container_name: explorer-tesseract
    restart: always
    volumes:
      - ./data/node:/data

  mongo:
    image: mongo
    container_name: explorer-db
    restart: always
    volumes:
      - ./data/db:/data/db
      - ./data/initdb.d:/docker-entrypoint-initdb.d
    environment:
      MONGO_INITDB_DATABASE: explorerdb
      MONGO_INITDB_ROOT_USERNAME: iquidus
      MONGO_INITDB_ROOT_PASSWORD: 3xp!0reR

  mongo-express:
    image: mongo-express
    container_name: explorer-debug
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: iquidus
      ME_CONFIG_MONGODB_ADMINPASSWORD: 3xp!0reR

  explorer:
    image: macterra/tesseract-explorer
    container_name: explorer-ui
    depends_on:
      - node
      - mongo
    restart: always
    ports:
      - 3001:3001
